### ISSUE TITLE
Bug: phantomjs REPL opens in the remote_file not_if guard

### ISSUE THREAD

**Issue by prashantrajan** [customink-webops/phantomjs#15]
Nasty suprise! Vagrant provisioning doesn't catch this.

When running on a _real_ server the `not_if` guard clause (https://github.com/customink-webops/phantomjs/blob/master/recipes/source.rb#L43) causes the phantomjs repl to open up and hang the chef-client run.

`/usr/local/bin/phantomjs` starts the repl.

**Comment by sethvargo** [comment]
@prashantrajan so much for testing... What OS? And this sounds like a bug in phantomjs then. If they are opening a REPL when someone asks for the version then... :facepunch:

**Comment by prashantrajan** [comment]
`not_if   { `/usr/local/bin/phantomjs && /usr/local/bin/phantomjs --version`.strip == version }`

The contents of that ruby block shells out - `/usr/local/bin/phantomjs` runs first (which opens a REPL), waits for a `ctrl command` (to exit REPL) and then executes `&& /usr/local/bin/phantomjs --version` which returns the version as expected.

The issue is that in a real chef-client run the ctrl command isn't given so it just waits.

We should just use ruby in the guard clause to test for the existence of the binary as per #16

This also avoids the strange non terminating error on the first run when the binary doesn't exist.

**Comment by prashantrajan** [comment]
fixed in #16
