### ISSUE TITLE
Once installed, subsequent attempts prompt at phantomjs>

### ISSUE THREAD

**Issue by leehambley** [customink-webops/phantomjs#18]
![screen shot 2013-07-04 at 8 56 45 am](https://f.cloud.github.com/assets/18952/747873/0ce3b4f2-e477-11e2-9f75-37e985ce9d3a.png)

On the first run through this works perfectly, looking at the source, I can only assume the problem is [here](https://github.com/customink-webops/phantomjs/blob/master/recipes/source.rb#L43).

**Comment by sethvargo** [comment]
@leehambley the problem is that line, but not on master (#16). This is fixed, but frankly, I totally forgot to release a new version :smile:. I'll do that now.

**Comment by sethvargo** [comment]
Released in https://github.com/customink-webops/phantomjs/releases/v1.0.2

**Comment by leehambley** [comment]
Thanks @sethvargo
