### ISSUE TITLE
Chocolatey dependency fails to install on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by beerlington** [customink-webops/phantomjs#22]
This used to install on Ubuntu with Chocolatey 0.0.5, but they recently bumped to 0.1.0 and it no longer installs. The Chocolatey [README](https://github.com/chocolatey/chocolatey-cookbook#requirements) says it requires Windows so I guess it makes sense that it wouldn't install on Ubuntu. Any ideas how to get around this issue?

![screen shot 2014-02-24 at 1 29 09 pm](https://f.cloud.github.com/assets/77580/2251917/f24d9150-9da1-11e3-9ae2-3b95655ed39e.png)

**Comment by sethvargo** [comment]
That error is because your version of Chef is too old. You need at least Chef 11 for `use_inline_resources`
