### ISSUE TITLE
Source download signature has changed

### ISSUE THREAD

**Issue by jakekdodd** [customink-webops/phantomjs#30]
The URL pattern for source downloads has changed as of version 2.0.0. It's been simplified to `#{base_url}/phantomjs-#{version}-source.zip`

It looks like this cookbook is no longer being maintained...if I made a PR with an update that supports versions 2.x.x of PhantomJS, would you be interested?

**Comment by jakekdodd** [comment]
So after reading through https://github.com/ariya/phantomjs/issues/12948, this may change soon. Maybe keep this on the back burner and revisit it when the PhantomJS folks have figured things out

**Comment by MOZGIII** [comment]
Any updates?

**Comment by drewbailey** [comment]
current work around for me at least..

``` ruby
node['phantomjs']['base_url'] = 'https://bitbucket.org/ariya/phantomjs/downloads'
node['phantomjs']['version'] = '2.1.1'
```

**Comment by sterago** [comment]
@drewbailey thanks for sharing your solution. I get a 403 doing that, and I believe is because of the captcha. Do you see that as well?

**Comment by drewbailey** [comment]
I was using this for my local vagrant which I haven't needed to reprovision in a while, the captcha didn't use to be there ☹️ I would probably just download and host it on s3 if I needed to do it again
