### ISSUE TITLE
Release new version to the community.opscode.com site

### ISSUE THREAD

**Issue by cap10morgan** [customink-webops/phantomjs#5]
Can you release a new version of this to the community.opscode.com site so that we can all enjoy the corrected download paths for phantomjs? Thanks!

**Comment by sethvargo** [comment]
Done: http://community.opscode.com/cookbooks/phantomjs

Sorry. Ran into issues with chefignore sucking and I can't yank other versions, so it magically jumped to v0.0.10 :(

**Comment by cap10morgan** [comment]
Thanks @sethvargo
